name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Nix check
        run: nix flake check

      - name: cabal-shell hash
        run: nix-shell test/cabal.nix --command 'which ghc && which cabal && exit'

      - name: cabal-shell flake
        run: nix-shell test/cabal.nix --arg use-hash false --command 'which ghc && which cabal && exit'

      - name: stack-shell hash
        run: nix-shell test/stack.nix --command 'which ghc && which stack && exit'

      - name: stack-shell flake
        run: nix-shell test/stack.nix --arg use-hash false --command 'which ghc && which stack && exit'

      - name: Formatting
        run: nix run github:tbidne/nix-hs-tools/0.6.1#nixpkgs-fmt -- --check
